# -*- coding: utf-8 -*-
"""Day4 Dataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114-OIYKf0Na4EgsAvamJYQIinFrda0ly
"""

from google.colab import drive
drive.mount('/content/drive')

# load the data
import pandas as pd
import numpy as np
import sklearn

data = pd.read_csv("/content/drive/MyDrive/50_Startups.csv")

data.head()

# check for missing values
data.isnull().sum()

# Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data.head()

from sklearn.preprocessing import scale

from sklearn.model_selection import train_test_split

# Awn creation = Tensorflow and keras
import tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense