# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gm2upK41MIHOl7ONk4mbR1Cn3qI-DIJL
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import sklearn

data = pd.read_csv("/content/drive/MyDrive/Day -4 -dataset/Data1.csv")

data.head()

data.tail()

data.shape

data.describe

data.mean()

dir(data)

data.iloc[1,:]

data.loc[1]

# dealing with missing value
data.isnull().sum()

data['Age'].fillna(data['Age'].mean())

data.isnull().sum()

data['Age'].fillna(data['Age'].mean(),inplace = True)

data.isnull().sum()

data['Salary'].fillna(data['Salary'].mean(),inplace = True)

data['Country'].value_counts()

data['Salary'].fillna(data['Salary'].median(),inplace = True)

data['Salary'].fillna("France",inplace = True)

# dealing with outliers
import seaborn as sns

sns.boxplot(data['Age'])

# upper extreme = q3+1.5*IQR
# lower extreme = q1-1.5*IQR
# IQR = q3-q1
qnt = data.quantile(q =[0.25,0.75])

qnt

IQR = qnt.loc[0.75]-qnt.loc[0.25]

IQR

upper_extreme = qnt.loc[0.75]+1.5*IQR

upper_extreme

upper_extreme = qnt.loc[0.25]-1.5*IQR

upper_extreme

# missing
from sklearn.impute import SimpleImputer

# intialize
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

