# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxluJVhb6FbWF-DwHxgw6coH0xIS6okq
"""

ls

cd/content/drive/MyDrive/Day -4 -dataset/CNN

ls

pwd

!unzip Animal_Dataset.zip

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale= 1./255,horizontal_flip = True,vertical_flip = True,zoom_range = 0.2)

test_datagen = ImageDataGenerator(rescale= 1./255)

x_train = train_datagen.flow_from_directory(r"/content/drive/MyDrive/day-4-dataset/CNN/dataset/Training",target_size = (64,64),
                                            class_mode = "categorical",batch_size = 24)